# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626c5f8c3c049c42c76fc3f998edc4a7c7a666022c6ab1308579902276d77f0c499234c46d318b545561cd9dd88bc6f67ba669ccb62afca8725460be50f610c8

test:
  secret_key_base: 7e0202328bc4f0d2533e5cc910e7a97b2396ac4b9a3a09d05d0b3d9fce7d869c197c5be4b1a9a56146161f4b673635ed3225dcc3357a768dacc670815ee3a4e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
